---
title: "Untitled"
output: bookdown::html_document2
bibliography: '`r rbbt::bbt_write_bib("data/info_projecticum_dsfb2.json", overwrite = TRUE)`'
date: "2023-04-25"
---

# introduction projecticum

when an organism ages multiple bodily factors will decrease in function. eyesight , hearing and muscle strength are all examples of this. In case of muscle strength in which muscles mass and function decreases is called sacropenia. Normal and mostly young muscle react on the environmental stimuli to grow such as insulin and leucine. when stimulated they make muscle protein this processes is called muscle protein synthesis (MPS). This process needs to be up kept to counter natural muscle decay. In aged individuals it is shown that due a resistance to stimuli such as insulin and leucine and elderly individuals perform little muscle training, that the balance between MPS and natural muscle decay is in favor the decay of muscles and so causes sacropenia (@dijkImprovedMuscleFunction2016). 

Further research (@dijkDifferentialEffectsLeucine2018) shows that leucine is a important factor in the pathway of MPS. The first evidence of this was by feeding young rats a single meal with a high leucine concentration after inspecting the muscles of these rats they showed a higher amount of MPS. additional it also proved that rats who were fed a higher dose of leucine showed more MPS than those with a low dose of leucine revealing a connection between the concentration and the reaction. therefore it showed promise to possibly combat sacropenia in older rats.

furthermore luecine controls MPS by being able to stimulate the Mthor pathway the mthor pathway can later stimulate the other other factors such as p70s6k and 4E-BP1 these factors influence the mRNA translation which results in more MPS in muscle cells. These factors were the start of many experiments looking at the different effects of leucine, such as what other factors are involved, different administration methods, and the effects of one or more doses spread over a longer period of time.

In the following research it turned out it was not as easy as firstly thought. It shows that older individuals have become more resistent to leucine with age (@vandijkSarcopeniaOlderMice2017) & (@boirieFastDigestiveProteins2018) In order for leucine to work the fed the older rats a higher dose than one would a normal rat and it was seen after eating this meal the rats did have a higher MPS then before eating the meal (@rieuLeucineSupplementedMealFeeding2003).

One of the most used proteins in this type of research is the whey protein. this protein is quick to digest and is rich with the leucine amino-acid. this protein has a very positive effect on the MPS.
 
Currently a research team by nutricia is looking into how leucine contributes to MPS and if there are plant based alternatives which can have similar effects as the whey protein. after giving the mice one of the experimental plant based protein their aminoacid values are measured. All of these value are compared. The results of this experiment gives a mountain of data to be decoded. to visualize all of this data so it would be easier to compare nutricia called in the help of the HU (hogeschool Utrecht) and their data science students.  



