---
title: "Covid data with parameters"
output: html_document
author: "Berrit Kievith"
date: "2023-05-25"
params:
  year:
    label: "Year"
    value: 2021
    input: slider
    min: 2020
    max: 2022
    step: 1
    sep: ""
  month:
    label: "month"
    value: 8
    input: slider
    min: 1
    max: 12
    step: 1
    sep: ""
  country:
    label: "country:"
    value: Croatia
    input: select
    choices: [Austria  ,Belgium, Bulgaria, Croatia ,Cyprus ,Czechia  ,Denmark, Estonia ,Finland,  France , Germany  ,Greece Hungary, Iceland, Ireland, Italy , Latvia  , Liechtenstein, Lithuania,  Luxembourg , Malta, Netherlands, Norway,  Poland, Portugal , Romania, Slovakia ,Slovenia, Spain ,Sweden ]


---


## loading the data
first we are going to load the libraries into R studio
```{r loading in the data , message=FALSE , warning=FALSE}
#these libraries need to be loaded

library(utils)

#read the Dataset sheet into “R”. The dataset will be called "data".
data <- read.csv("https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
```
## inspecting the data

```{r create graphs , message=FALSE , warning=FALSE}
library(tidyverse)

unique(data$countriesAndTerritories)
unique(data$year)
```
## Covid cases in `r params$country`

```{r, message=FALSE , warning=FALSE}
data %>% filter(countriesAndTerritories == params$country) %>% filter(year == params$year) %>% filter(month == params$month)  %>% ggplot(aes(x= day , y = cases)) + geom_point(aes(color = "lightblue")) + geom_line(aes(color = "lightblue")) + scale_color_manual(values= "lightblue") + theme(legend.position = "none") + labs(title = paste("covid cases" , params$country , params$month , params$year , sep = " "))
```
## Covid death  cases in `r params$country`
```{r, message=FALSE , warning=FALSE}
data %>% filter(countriesAndTerritories == params$country) %>% filter(year == params$year) %>% filter(month == params$month)  %>% ggplot(aes(x= day , y = deaths )) + geom_point(aes(color = "darkred")) + geom_line(aes(color = "darkred")) + scale_color_manual(values= "darkred") + theme(legend.position = "none") + labs(title = paste("covid deaths" , params$country , params$month , params$year , sep = " "))
```

